packages:
  # Baseline things necessary to build any Debian package.
  - build-essential fakeroot devscripts
  # Required by our git-buildpackage workflow.
  - git git-buildpackage
  # Optional; but just by having it here, we will get -dbgsym packages without having to modify the
  # packages' control files.
  - pkg-create-dbgsym

  # # Do we need to manually install lintian?
  # - lintian
  
