packages:
  # Baseline things necessary to build any Debian package.
  - build-essential fakeroot devscripts equivs
  - dpatch lintian quilt
  # Starting with artful, `debhelper` must be installed for `equivs`
  - debhelper
  # Required by our git-buildpackage workflow.
  - git git-buildpackage pristine-tar
  # Optional; but just by having it here, we will get -dbgsym packages without having to modify the
  # packages' control files.
  - pkg-create-dbgsym

  # Do we need to manually install lintian?
  - lintian
  # ca-certificates
  # dput
  # patchutils

  # Added to resolve noisy warnings: 'warning: File::FcntlLock not available; using flock which is not NFS-safe'
  # (Ref.: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=677865)
  - libfile-fcntllock-perl
