# With parts cribbed from https://github.com/dochang/docker-debuild

FROM FROM_IMAGE
MAINTAINER Kevin Kelley <kelleyk@kelleyk.net>

ADD apt-config.sh entry.sh build-package.sh /
RUN chmod +x /apt-config.sh && /apt-config.sh && rm apt-config.sh

VOLUME ["/source", "/build"]
WORKDIR /build
CMD "/entry.sh"
