# With parts cribbed from https://github.com/dochang/docker-debuild

FROM FROM_IMAGE
MAINTAINER Kevin Kelley <kelleyk@kelleyk.net>

ADD apt-config.sh /apt-config.sh
RUN chmod +x /apt-config.sh
RUN /apt-config.sh && rm apt-config.sh

VOLUME ["/source"]
VOLUME ["/build"]
WORKDIR /build

CMD "/entry.sh"
ADD entry.sh /entry.sh
ADD build-package.sh /build-package.sh
